spring:
  aop:

    proxy-target-class: true
  application:
    name: online-mall-application
  datasource:
    url: jdbc:mysql://localhost:3306/online_mall
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2004momingqin
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      database: 1
mybatis-plus:
  mapper-locations: classpath*:com/scutmmq/mapper/**/*.xml
  type-aliases-package: com.scutmmq.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: web-management-ai
    region: cn-beijing